DROP TABLE IF EXISTS monitors;

DROP PROCEDURE IF EXISTS add_monitor;

DROP FUNCTION IF EXISTS get_monitor;

DROP TABLE IF EXISTS users;

DROP FUNCTION IF EXISTS create_user;

DROP FUNCTION IF EXISTS get_user_by_username;
